"""Change users and recipes tables

Revision ID: 1903d4e2edc2
Revises: 04b41dfcb789
Create Date: 2022-09-10 10:27:31.002983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1903d4e2edc2'
down_revision = '04b41dfcb789'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('type', sa.String(), nullable=False))
    op.add_column('recipes', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('recipes', sa.Column('cooking_steps', sa.ARRAY(sa.Text()), nullable=False))
    op.add_column('recipes', sa.Column('hashtags', sa.ARRAY(sa.String()), nullable=False))
    op.add_column('recipes', sa.Column('image', sa.String(), nullable=False))
    op.add_column('recipes', sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False))
    op.add_column('recipes', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('recipes', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'updated_at')
    op.drop_column('recipes', 'created_at')
    op.drop_column('recipes', 'is_active')
    op.drop_column('recipes', 'image')
    op.drop_column('recipes', 'hashtags')
    op.drop_column('recipes', 'cooking_steps')
    op.drop_column('recipes', 'description')
    op.drop_column('recipes', 'type')
    # ### end Alembic commands ###
