"""Add user_id field to recipes table

Revision ID: 61de70f7b3eb
Revises: 1903d4e2edc2
Create Date: 2022-09-10 21:40:00.972693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61de70f7b3eb'
down_revision = '1903d4e2edc2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'recipes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.drop_column('recipes', 'user_id')
    # ### end Alembic commands ###
