"""make image field nullable in recipes table

Revision ID: 799d88515925
Revises: 61de70f7b3eb
Create Date: 2022-09-13 23:02:00.797889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '799d88515925'
down_revision = '61de70f7b3eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
